version: 1.1.{build}

# NOTE .NET Core SDK is already installed in the build worker image Visual Studio 2017
# so the `install` section is not required

image: Visual Studio 2017

configuration: Release

# skip_commits:
#   message: /\[release\]/
#   except:
#     appveyor_repo_tag: true

init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true

artifacts:
  - path: '**\*.nupkg'
    name: Package
    type: NuGetPackage
  - path: bin/Release
    name: Release
    type: Zip

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

before_build:
  - cmd: dotnet --info
  - cmd: dotnet restore --verbosity m
build_script:
  - cmd: dotnet pack
  - cmd: cd Framework\AspNetCore && dotnet pack && cd ..\..\

test_script:
  - cmd: cd Example\AspNetCore
  - cmd: dotnet restore --verbosity m
  - cmd: dotnet run --shutdown 5

deploy:
  - provider: NuGet
    artifact: Package
    api_key: $(NUGET_KEY)
    skip_symbols: false
    on:
      appveyor_repo_tag: true        # deploy on tag push only
  - provider: GitHub
    artifact: Release
    auth_token: $(GITHUB_KEY)
    draft: true
    force_update: true
    on:
      branch: master                 # release from master branch only
      appveyor_repo_tag: true        # deploy on tag push only